### ISSUE TITLE
typo "he" instead "they" on the Getting started page

### ISSUE THREAD

**Issue by Patrick-Lenihan** [chocoteam/website#17]
Hello,
# The issue
I noticed a small typo in the [getting started documentation page](https://github.com/chocoteam/website/blob/master/content/en/docs/Getting%20started/_index.md). On line 59 of the markdown file  under the section "As a stand-alone application" the text is as follows:
 "When one wants to manually `adds` choco-solver as a dependency of a project, `he` should pay attention to the following"

# My suggestion
as an improvement:
- I suggest "he" should be replaced with "they" to make the statement more general instead of specific to men.
- I suggest "adds" should be replaced with "add" for proper subject verb agreement.

making:
`When one wants to manually add choco-solver as a dependency of a project, they should pay attention to the following:`

**Comment by cprudhom** [comment]
Thank you for contributing
