### ISSUE TITLE
Minimum required Java version?

### ISSUE THREAD

**Issue by Holt59** [chocoteam/website#7]
The "Getting Started" page mentions Java 11 while the README mentions JDK8+. The last release to mention a change in JDK version is 4.10.3, which mentions compatibility with JDK8 and JDK9+.

Is the latest release of Choco Solver compatible with JDK8? If so, the documentation should probably be updated.

**Comment by cprudhom** [comment]
Well, Choco-solver is compiled to JDK 8 and compatible to JDK 9 (modularity).
Maybe one day, we will leave Java 8 to another LTS (like JDK 17?) but there is no roadmap to that.
